# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI|CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install package for node_modules
      run: yarn
      
    - name: Running test coverage
      run: yarn test:coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install  Dependencies
        run: yarn
      - name: Build Project
        run: yarn build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./dist